theme: jekyll-theme-minimal
title: The Evolution of Gender and Ethnic Representation in Cinema
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
